# Machine Learning Zoomcamp

## 1.7 Introduction to NumPy

Plan:

- Creating arrays
- Multi-dimensional arrays
- Randomly generated arrays
- Element-wise operations
    - Comparison operations
    - Logical operations
- Summarizing operations

In [10]:
import numpy as np

In [11]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

# Creating arrays

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [17]:
a = np.array([1, 2, 3, 5, 7, 12])

In [19]:
a[2] = 10

In [20]:
a 

array([ 1,  2, 10,  5,  7, 12])

In [21]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [23]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Multi-dimensional arrays

In [25]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
n[0]

array([1, 2, 3])

In [31]:
n[0, 1]

np.int64(2)

In [34]:
n[:,2]

array([3, 6, 9])

In [36]:
n[:,2] = [0, 0, 0]
n

array([[1, 2, 0],
       [4, 5, 0],
       [7, 8, 0]])

# Randomly generated arrays

In [39]:
np.random.rand(5, 2)

array([[0.18560879, 0.02791009],
       [0.85207083, 0.81174598],
       [0.33745083, 0.26848963],
       [0.61493327, 0.3009641 ],
       [0.92242246, 0.49587929]])

In [42]:
np.random.seed(42)
np.random.rand(5, 2)

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615],
       [0.60111501, 0.70807258]])

In [44]:
np.random.randn(5, 2)

array([[-0.90802408, -1.4123037 ],
       [ 1.46564877, -0.2257763 ],
       [ 0.0675282 , -1.42474819],
       [-0.54438272,  0.11092259],
       [-1.15099358,  0.37569802]])

In [46]:
#np.random.randint(low=0, high=100, size=(5,2))
np.random.randint(0, 100, (5,2))

array([[83, 91],
       [59, 70],
       [43,  7],
       [46, 34],
       [77, 80]])

# Element-wise operations

In [47]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [48]:
a + 1

array([1, 2, 3, 4, 5])

In [49]:
a * 2

array([0, 2, 4, 6, 8])

In [50]:
a / 2

array([0. , 0.5, 1. , 1.5, 2. ])

In [53]:
b = (10 + (a * 2)) ** 2 / 100

In [56]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [57]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

In [58]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

# Comparison operations

In [59]:
a

array([0, 1, 2, 3, 4])

In [60]:
a >= 2

array([False, False,  True,  True,  True])

In [61]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [62]:
a > b

array([False, False,  True,  True,  True])

In [64]:
a[a > b]

array([2, 3, 4])

# Logical operations

# Summarizing operations

In [65]:
a

array([0, 1, 2, 3, 4])

In [66]:
a.min()

np.int64(0)

In [67]:
a.max()

np.int64(4)

In [68]:
a.sum()

np.int64(10)

In [69]:
a.mean()

np.float64(2.0)

In [70]:
a.std()

np.float64(1.4142135623730951)

In [71]:
n

array([[1, 2, 0],
       [4, 5, 0],
       [7, 8, 0]])

In [72]:
n.min()

np.int64(0)